services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=abcd@123
      - TZ=Asia/Dhaka
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    restart: always

volumes:
  sql-data: