services:
  redis_stack:
    image: redis/redis-stack-server:latest
    container_name: redis-stack
    command: redis-stack-server --requirepass 12345  # Updated password
    ports:
      - 6379:6379 
    volumes:
      - redis_data:/data  
    restart: always

volumes:
  redis_data: